# Generated by Django 4.1.1 on 2022-09-29 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_add_zip_to_address"),
    ]

    operations = [
        migrations.RunSQL(
            """            
                INSERT INTO store_collection (title)
                VALUES ('collection2')
            """,
            """
                DELETE FROM store_collection 
                WHERE title='collection2'
            """,
        )
    ]
